spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music_app
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

server:
  port: 3000
  servlet:
    context-path: /api/v1

jwt:
  signerKey: zN/gkNC3dQIrDfQQ2Yyv9zo/OyEc6t/BjI20zDPNY+v2i1W69TVL2rJNJkXsGLi7
  valid-duration: 300
  refreshable-duration: 604800

role:
  user: f1519cdd-4b96-45bb-bfcf-5556ebab50ee
  admin: 1f99c255-a5b9-4f66-99de-5fac6febe6ee

file:
  upload-dir: public/images

track:
  upload-dir: public/tracks
